"use client";

import { useState } from "react";
import Reveal from "./Reveal";

// TODO: replace with the inbox you want requests to land in
const REQUEST_EMAIL = "hello@anybook.co";

export default function RequestSection() {
  const [title, setTitle] = useState("");
  const [author, setAuthor] = useState("");
  const [email, setEmail] = useState("");
  const [status, setStatus] = useState<{ text: string; color: string }>({
    text: "",
    color: "",
  });

  function handleSubmit(e: React.FormEvent<HTMLFormElement>) {
    e.preventDefault();
    const trimmedTitle = title.trim();

    if (!trimmedTitle) {
      setStatus({ text: "Add a book title first.", color: "var(--rust)" });
      document.getElementById("reqTitle")?.focus();
      return;
    }

    const subject = `Book request: ${trimmedTitle}`;
    let body = `Book title: ${trimmedTitle}\n`;
    if (author.trim()) body += `Author: ${author.trim()}\n`;
    if (email.trim()) body += `Notify me at: ${email.trim()}\n`;
    body += `\nSent from the AnyBook request form.`;

    const mailtoLink = `mailto:${REQUEST_EMAIL}?subject=${encodeURIComponent(
      subject
    )}&body=${encodeURIComponent(body)}`;

    setStatus({ text: "Opening your email app…", color: "var(--sage)" });
    window.location.href = mailtoLink;
  }

  return (
    <section id="request">
      <div className="wrap diff">
        <Reveal>
          <div className="eyebrow">Written by readers, not generated by AI</div>
          <h2>A library that grows one request at a time.</h2>
          <p>
            Most summary apps run your book through an algorithm and hand
            back whatever comes out. AnyBook doesn&apos;t. Every summary is
            read and written by us, chapter by chapter, before it goes on
            the shelf.
          </p>
          <p>Search the library. If your title isn&apos;t there yet, send it our way and we&apos;ll add it.</p>
        </Reveal>
        <Reveal delay={2}>
          <form className="request-card" id="requestForm" noValidate onSubmit={handleSubmit}>
            <div className="req-tag">Request a title</div>
            <h3>Don&apos;t see your book?</h3>
            <div className="field">
              <label htmlFor="reqTitle">Book title</label>
              <input
                type="text"
                id="reqTitle"
                name="reqTitle"
                placeholder="e.g. The Odyssey"
                required
                autoComplete="off"
                value={title}
                onChange={(e) => setTitle(e.target.value)}
              />
            </div>
            <div className="field">
              <label htmlFor="reqAuthor">
                Author <span style={{ opacity: 0.6 }}>(optional)</span>
              </label>
              <input
                type="text"
                id="reqAuthor"
                name="reqAuthor"
                placeholder="e.g. Homer"
                autoComplete="off"
                value={author}
                onChange={(e) => setAuthor(e.target.value)}
              />
            </div>
            <div className="field">
              <label htmlFor="reqEmail">
                Your email{" "}
                <span style={{ opacity: 0.6 }}>
                  (optional, so we can tell you when it&apos;s up)
                </span>
              </label>
              <input
                type="email"
                id="reqEmail"
                name="reqEmail"
                placeholder="you@example.com"
                autoComplete="off"
                value={email}
                onChange={(e) => setEmail(e.target.value)}
              />
            </div>
            <button type="submit" className="btn btn-gold">
              Send request
            </button>
            <div className="req-status" aria-live="polite" style={{ color: status.color }}>
              {status.text}
            </div>
            <div className="req-hint">
              This opens your email app with the details filled in, addressed
              to us. No account, no bot in between.
            </div>
          </form>
        </Reveal>
      </div>
    </section>
  );
}
